name: CI/CD-MANOJ

on: workflow_dispatch

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker hub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: manojdsingh/mywebapp:latest  # Please change the username here

      - name: Docker Login
        id: Docker_Login
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker Container Run
        id: Docker_Container_Run
        run: |
          docker image pull manojdsingh/mywebapp
            docker container stop mywebapp-prod
            docker container prune -f
            docker run -d --name mywebapp-prod --restart unless-stopped -p 9020:80 -p 9021:443 manojdsingh/mywebapp
            docker image prune -f         
        
       
      
